todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('doing/', views.doing, name='doing'),
    path('done/', views.done, name='done'),
    path('delete/', views.delete, name='delete')
]

todos/models.py
from django.db import models
import datetime
from django.utils import timezone

class TodoItem(models.Model):
    text = models.CharField(max_length=100)
    added_date = models.DateTimeField(auto_now_add=True)
    doing = models.BooleanField(default=False)
    done = models.BooleanField(default=False)

    def was_added_recently(self):
        return self.added_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.text

todos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import TodoItem

def index(request):
    items = TodoItem.objects.all()
    context = {"todos": items}
    return render(request, 'todos/index.html', context)

def add(request):
    if request.method == 'POST':
        item = TodoItem(text=request.POST['item'])
        item.save()
        return redirect("todos:index")
    else:
        return render(request, "todos/index.html")

def doing(request):
    if request.method == 'POST':
        item = TodoItem.objects.get(pk=request.POST['doing_id'])
        item.doing = True
        item.done = False
        item.save()
        return redirect('todos:index')
    else:
        return render(request, "todos/index.html")


def done(request):
    if request.method == 'POST':
        item = TodoItem.objects.get(pk=request.POST['id'])
        item.done = True
        item.doing = False
        item.save()
        return redirect("todos:index")
    else:
        return render(request, "todos/index.html")

def delete(request):
    if request.method == 'POST':
        item = TodoItem.objects.get(pk=request.POST['delete_id'])
        item.delete()
        return redirect("todos:index")
    else:
        return render(request, "todos/index.html")

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:wght@300&display=swap" rel="stylesheet">
    <title>To-do List</title>
</head>
<body style="background-color: #104E2E; font-family: 'Spline Sans Mono', monospace;">
    <div class="container-fluid">
        {% block content %}{% endblock content %}  
    </div>
</body>
</html>

todos/templates/todos/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="text-uppercase display-3 text-center text-white mt-3"><a href="https://www.djangoproject.com/"><img src="{% static 'django.png' %}" width="150px"/></a>To-Do List</h1>

    <div style="background-color: #ffffffdd;" class="card d-flex flex-column flex-sm-row text-center display-6 mt-4">
        <div class="col-12 col-md-4 pe-0">
            <div class="d-flex flex-column">
                <div class="btn btn-danger fs-3 mb-2">To-do</div>
            <form method='POST' action="{% url 'todos:add' %}">
                {% csrf_token %}
                    <div class="input-group">
                        <div class="d-flex w-100 align-items-center justify-content-center ps-2">
                            <input type="text" name="item" id="item" class="form-control me-2" autofocus/>
                            <button class="btn btn-dark me-3 rounded-circle" type="submit">+</button>
                        </div>
                    </div>
            </form>
            
            <div class="d-flex flex-column mt-1 ps-2">
                {% for todo in todos %}
                <div class="d-flex align-items-center">
                    {% if not todo.doing and not todo.done %}
                        <form action="{% url 'todos:done' %}" method="POST">
                            {% csrf_token %}
                            <input onchange="this.form.submit()" type="checkbox" id="done" value="done" style="height: 15px; width: 15px;" class="form-check-input me-2 mt-3 " />
                            <input type="hidden" name="id" value="{{ todo.id }}" />
                        </form>
                        <form action="{% url 'todos:doing' %}" method='POST'>
                            {% csrf_token %}
                            <div class="d-flex align-items-center">
                                <div class="fw-bold text-start text-break ps-2 mb-1" ><u>{{ todo }}</u></div>
                                <button type="submit" class="btn btn-warning ms-3 me-2 my-2 h-50 float-end">doing</button>
                            </div>
                            <input type="hidden" value="{{ todo.id }}" name="doing_id" />
                        </form>
                        <form action="{% url 'todos:delete' %}" method='POST'>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger fw-bold my-2 float-end rounded-circle">&#10005;</button>
                            <input type="hidden" name="delete_id" value="{{ todo.id }}" />
                        </form>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>

        </div>
        
        <div class="col-12 col-md-4 pe-0">
            <div class="d-flex flex-column">
                <div class="btn btn-primary fs-3 mb-2 ">Doing</div>
                {% for t in todos %}
                    {% if t.doing and not t.done %}
                    <div class="d-flex w-100 align-items-center justify-content-center mb-2">
                            <form action="{% url 'todos:done' %}" method="POST">
                                {% csrf_token %}
                                <input style="width: 15px; height: 15px;" onchange="this.form.submit()" class="form-check-input mx-2 mt-2 mt-md-3" type="checkbox"/>
                                <input type="hidden" name="id" value="{{ t.id }}"/>
                            </form>
                            <mark class="text-break w-100 px-3 text-start rounded-pill text-white" style="background-color: #104E2E;">
                                {{ t }}
                            </mark>
                            <form action="{% url 'todos:delete' %}" method='POST'>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger fw-bold float-end rounded-circle ms-1">&#10005;</button>
                                <input type="hidden" name="delete_id" value="{{ t.id }}" />
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="col-12 col-md-4">
            <div class="d-flex flex-column px-0">
                <div class="btn btn-success fs-3 mb-2">Done</div>
                <ul class="list-unstyled">
                    {% for t in todos %}
                        {% if t.done and not t.doing %}
                            <li>
                                <div class="fw-bolder text-start text-break ps-3 mb-1" ><del style="color: rgb(206, 82, 195);">{{ t }}</del></div>
                            </li>
                        {% endif %}                    
                    {% endfor %}
                </ul>
                </div>
            </div>
        </div>

    </div>




{% endblock content %}